// 자동 생성 파일: tools/gen-layout.mjs (직접 고치지 말고 생성기를 고칠 것)
// 출처: libhangul (https://github.com/libhangul/libhangul) data/keyboards/hangul-keyboard-{2,39,3f}.xml.template
//   commit 5094421d9586294b2aad09924b9a54e2e6060f06 (2026-09-14)
// 검증 상태 (2026-10-04, 키별 대조. KS X 5002 PDF·한글문화원 인쇄 도표는 구하지 못함 → 표준 원문 대조는 미확인):
//   - 두벌식 자모 52키: libhangul = GNU Emacs lisp/leim/quail/hangul.el (2-bulsik) = uim scm/byeoru.scm (hangul2). 불일치 0.
//   - 세벌식 390 자모+기호: libhangul = Emacs (390) = uim (strict390). 불일치 0.
//   - 세벌식 최종 자모: libhangul = Emacs (final) = uim (strict3final). 불일치 0.
//   - 세벌식 최종 기호: Emacs와 전부 일치. uim만 '|' 가 ₩ (libhangul·Emacs는 백슬래시). 그 행에만 적었다.
//   - 항등 매핑(키가 자기 문자로 나오는 것)은 생략했다. 표에 없는 키 = 그대로 통과.
import { cho, cons, jong, jung, lit } from './keydef'
import type { KeyDef } from './keydef'

/** 두벌식 (KS X 5002). cons = 초성·종성 겸용 자음. */
export const DUBEOLSIK: Readonly<Record<string, KeyDef>> = {
  "A": cons('ㅁ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "B": jung('ㅠ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "C": cons('ㅊ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "D": cons('ㅇ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "E": cons('ㄸ'),
  "F": cons('ㄹ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "G": cons('ㅎ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "H": jung('ㅗ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "I": jung('ㅑ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "J": jung('ㅓ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "K": jung('ㅏ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "L": jung('ㅣ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "M": jung('ㅡ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "N": jung('ㅜ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "O": jung('ㅒ'),
  "P": jung('ㅖ'),
  "Q": cons('ㅃ'),
  "R": cons('ㄲ'),
  "S": cons('ㄴ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "T": cons('ㅆ'),
  "U": jung('ㅕ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "V": cons('ㅍ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "W": cons('ㅉ'),
  "X": cons('ㅌ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "Y": jung('ㅛ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "Z": cons('ㅋ'), // 대문자=소문자와 동일 (libhangul·Emacs·uim 일치, KS X 5002 원문 미확인)
  "a": cons('ㅁ'),
  "b": jung('ㅠ'),
  "c": cons('ㅊ'),
  "d": cons('ㅇ'),
  "e": cons('ㄷ'),
  "f": cons('ㄹ'),
  "g": cons('ㅎ'),
  "h": jung('ㅗ'),
  "i": jung('ㅑ'),
  "j": jung('ㅓ'),
  "k": jung('ㅏ'),
  "l": jung('ㅣ'),
  "m": jung('ㅡ'),
  "n": jung('ㅜ'),
  "o": jung('ㅐ'),
  "p": jung('ㅔ'),
  "q": cons('ㅂ'),
  "r": cons('ㄱ'),
  "s": cons('ㄴ'),
  "t": cons('ㅅ'),
  "u": jung('ㅕ'),
  "v": cons('ㅍ'),
  "w": cons('ㅈ'),
  "x": cons('ㅌ'),
  "y": jung('ㅛ'),
  "z": cons('ㅋ'),
}

/** 세벌식 390 (libhangul id "39"). cho/jung/jong 은 키마다 고정된 역할. */
export const SEBEOLSIK_390: Readonly<Record<string, KeyDef>> = {
  "!": jong('ㅈ'),
  "'": cho('ㅌ'),
  "/": jung('ㅗ'),
  "0": cho('ㅋ'),
  "1": jong('ㅎ'),
  "2": jong('ㅆ'),
  "3": jong('ㅂ'),
  "4": jung('ㅛ'),
  "5": jung('ㅠ'),
  "6": jung('ㅑ'),
  "7": jung('ㅖ'),
  "8": jung('ㅢ'),
  "9": jung('ㅜ'),
  ";": cho('ㅂ'),
  "<": lit("2"),
  ">": lit("3"),
  "A": jong('ㄷ'),
  "B": lit("!"),
  "C": jong('ㄻ'),
  "D": jong('ㄺ'),
  "E": jong('ㅋ'),
  "F": jong('ㄲ'),
  "G": lit("/"),
  "H": lit("'"),
  "I": lit("8"),
  "J": lit("4"),
  "K": lit("5"),
  "L": lit("6"),
  "M": lit("1"),
  "N": lit("0"),
  "O": lit("9"),
  "P": lit(">"),
  "Q": jong('ㅍ'),
  "R": jung('ㅒ'),
  "S": jong('ㄶ'),
  "T": lit(";"),
  "U": lit("7"),
  "V": jong('ㅀ'),
  "W": jong('ㅌ'),
  "X": jong('ㅄ'),
  "Y": lit("<"),
  "Z": jong('ㅊ'),
  "a": jong('ㅇ'),
  "b": jung('ㅜ'),
  "c": jung('ㅔ'),
  "d": jung('ㅣ'),
  "e": jung('ㅕ'),
  "f": jung('ㅏ'),
  "g": jung('ㅡ'),
  "h": cho('ㄴ'),
  "i": cho('ㅁ'),
  "j": cho('ㅇ'),
  "k": cho('ㄱ'),
  "l": cho('ㅈ'),
  "m": cho('ㅎ'),
  "n": cho('ㅅ'),
  "o": cho('ㅊ'),
  "p": cho('ㅍ'),
  "q": jong('ㅅ'),
  "r": jung('ㅐ'),
  "s": jong('ㄴ'),
  "t": jung('ㅓ'),
  "u": cho('ㄷ'),
  "v": jung('ㅗ'),
  "w": jong('ㄹ'),
  "x": jong('ㄱ'),
  "y": cho('ㄹ'),
  "z": jong('ㅁ'),
}

/** 세벌식 최종 (libhangul id "3f"). */
export const SEBEOLSIK_FINAL: Readonly<Record<string, KeyDef>> = {
  "!": jong('ㄲ'),
  "\"": lit("·"),
  "#": jong('ㅈ'),
  "$": jong('ㄿ'),
  "%": jong('ㄾ'),
  "&": lit("“"),
  "'": cho('ㅌ'),
  "(": lit("'"),
  ")": lit("~"),
  "*": lit("”"),
  "-": lit(")"),
  "/": jung('ㅗ'),
  "0": cho('ㅋ'),
  "1": jong('ㅎ'),
  "2": jong('ㅆ'),
  "3": jong('ㅂ'),
  "4": jung('ㅛ'),
  "5": jung('ㅠ'),
  "6": jung('ㅑ'),
  "7": jung('ㅖ'),
  "8": jung('ㅢ'),
  "9": jung('ㅜ'),
  ":": lit("4"),
  ";": cho('ㅂ'),
  "<": lit(","),
  "=": lit(">"),
  ">": lit("."),
  "?": lit("!"),
  "@": jong('ㄺ'),
  "A": jong('ㄷ'),
  "B": lit("?"),
  "C": jong('ㅋ'),
  "D": jong('ㄼ'),
  "E": jong('ㄵ'),
  "F": jong('ㄻ'),
  "G": jung('ㅒ'),
  "H": lit("0"),
  "I": lit("7"),
  "J": lit("1"),
  "K": lit("2"),
  "L": lit("3"),
  "M": lit("\""),
  "N": lit("-"),
  "O": lit("8"),
  "P": lit("9"),
  "Q": jong('ㅍ'),
  "R": jong('ㅀ'),
  "S": jong('ㄶ'),
  "T": jong('ㄽ'),
  "U": lit("6"),
  "V": jong('ㄳ'),
  "W": jong('ㅌ'),
  "X": jong('ㅄ'),
  "Y": lit("5"),
  "Z": jong('ㅊ'),
  "[": lit("("),
  "\\": lit(":"),
  "]": lit("<"),
  "^": lit("="),
  "_": lit(";"),
  "`": lit("*"),
  "a": jong('ㅇ'),
  "b": jung('ㅜ'),
  "c": jung('ㅔ'),
  "d": jung('ㅣ'),
  "e": jung('ㅕ'),
  "f": jung('ㅏ'),
  "g": jung('ㅡ'),
  "h": cho('ㄴ'),
  "i": cho('ㅁ'),
  "j": cho('ㅇ'),
  "k": cho('ㄱ'),
  "l": cho('ㅈ'),
  "m": cho('ㅎ'),
  "n": cho('ㅅ'),
  "o": cho('ㅊ'),
  "p": cho('ㅍ'),
  "q": jong('ㅅ'),
  "r": jung('ㅐ'),
  "s": jong('ㄴ'),
  "t": jung('ㅓ'),
  "u": cho('ㄷ'),
  "v": jung('ㅗ'),
  "w": jong('ㄹ'),
  "x": jong('ㄱ'),
  "y": cho('ㄹ'),
  "z": jong('ㅁ'),
  "{": lit("%"),
  "|": lit("\\"), // uim byeoru만 "₩". libhangul·Emacs hangul.el은 이 값. KS/문화원 원문 미확인
  "}": lit("/"),
  "~": lit("※"),
}

